# Multi-actor pipeline: Stage 1 - Text preprocessing
# CPU-bound, fast processing with high parallelism

apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: preprocess
  namespace: default
spec:
  transport: rabbitmq

  scaling:
    enabled: true
    minReplicas: 0
    maxReplicas: 20 # High parallelism for fast CPU work
    queueLength: 10

  workload:
    kind: Deployment
    template:
      spec:
        containers:
        - name: asya-runtime
          image: text-preprocessor:latest
          env:
          - name: ASYA_HANDLER
            value: "preprocessor.clean_text"
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
